/* stm32u5_hash.c
 *
 * Copyright (C) 2014-2026 wolfSSL Inc.  All rights reserved.
 *
 * This file is part of wolfBoot.
 *
 * Contact licensing@wolfssl.com with any questions or comments.
 *
 * https://www.wolfssl.com
 */

#ifdef WHAL_CFG_STM32U5_HASH_INIT_DIRECT_API_MAPPING
#define WHAL_CFG_STM32WBA_HASH_INIT_DIRECT_API_MAPPING
#endif
#ifdef WHAL_CFG_STM32U5_HASH_SHA1_DIRECT_API_MAPPING
#define WHAL_CFG_STM32WBA_HASH_SHA1_DIRECT_API_MAPPING
#endif
#ifdef WHAL_CFG_STM32U5_HASH_SHA224_DIRECT_API_MAPPING
#define WHAL_CFG_STM32WBA_HASH_SHA224_DIRECT_API_MAPPING
#endif
#ifdef WHAL_CFG_STM32U5_HASH_SHA256_DIRECT_API_MAPPING
#define WHAL_CFG_STM32WBA_HASH_SHA256_DIRECT_API_MAPPING
#endif
#ifdef WHAL_CFG_STM32U5_HASH_HMAC_SHA1_DIRECT_API_MAPPING
#define WHAL_CFG_STM32WBA_HASH_HMAC_SHA1_DIRECT_API_MAPPING
#endif
#ifdef WHAL_CFG_STM32U5_HASH_HMAC_SHA224_DIRECT_API_MAPPING
#define WHAL_CFG_STM32WBA_HASH_HMAC_SHA224_DIRECT_API_MAPPING
#endif
#ifdef WHAL_CFG_STM32U5_HASH_HMAC_SHA256_DIRECT_API_MAPPING
#define WHAL_CFG_STM32WBA_HASH_HMAC_SHA256_DIRECT_API_MAPPING
#endif
#include "stm32wba_hash.c"
