/* unit-aurix-erased-fill.c
 *
 * Regression test: cacheSector() and programBytesToErasedFlash() in
 * hal/aurix_tc3xx.c filled uint32_t page buffers with the byte-valued
 * FLASH_BYTE_ERASED, so each word became 0x000000FF instead of
 * 0xFFFFFFFF. A one-byte write into an erased page then programmed
 * zeroes into the rest of the word.
 *
 * Extracts both functions (generated by the Makefile) and runs them
 * against an emulated tc3_flash_* API. Built twice, once per flag
 * polarity: default (erased = 0xFF), where the bug shows, and
 * WOLFBOOT_FLAGS_INVERT (erased = 0x00), where the fill must not
 * change.
 * Copyright (C) 2014-2026 wolfSSL Inc.  All rights reserved.
 *
 * This file is part of wolfBoot.
 *
 * Contact licensing@wolfssl.com with any questions or comments.
 *
 * https://www.wolfssl.com
 */

#include <check.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>

#include "wolfboot/wolfboot.h"

/* Target constants normally provided by the TC3xx IAP vendor headers
 * and the board build. */
#define RAMFUNCTION
#define TC3_PFLASH_PAGE_SIZE 0x200
#define TC3_FLASH_NOTBLANK 1
#define WOLFBOOT_SECTOR_SIZE 0x1000
#define GET_PAGE_ADDR(addr) \
    ((uintptr_t)(addr) & ~(TC3_PFLASH_PAGE_SIZE - 1))

/* RAM buffer to hold the contents of an entire flash sector (real:
 * hal/aurix_tc3xx.c). */
static uint32_t sectorBuffer[WOLFBOOT_SECTOR_SIZE / sizeof(uint32_t)];

/* Emulated PFlash: two sectors. */
#define FLASH_SIZE (2 * WOLFBOOT_SECTOR_SIZE)
static uint8_t g_flash[FLASH_SIZE];

static int tc3_flash_Program(uint32_t addr, const uint32_t *buf, uint32_t len)
{
    memcpy(g_flash + addr, buf, len);
    return 0;
}

static int tc3_flash_BlankCheck(uint32_t addr, uint32_t len)
{
    uint32_t i;

    for (i = 0; i < len; i++) {
        if (g_flash[addr + i] != FLASH_BYTE_ERASED)
            return TC3_FLASH_NOTBLANK;
    }
    return 0;
}

static void readPage32Aligned(uint32_t pageAddr, uint32_t *data)
{
    memcpy(data, g_flash + pageAddr, TC3_PFLASH_PAGE_SIZE);
}

void wolfBoot_panic(void)
{
    _exit(120);
}

/* The real functions under test (extracted by the Makefile). */
#include "aurix_erased_extract.h"

static void setup(void)
{
    memset(g_flash, 0xAA, sizeof(g_flash));
}

static void teardown(void)
{
}

static void fill(uint8_t *buf, size_t len, uint8_t base)
{
    size_t i;

    for (i = 0; i < len; i++)
        buf[i] = (uint8_t)(base + i);
}

/* A partial-page write must leave the rest of the page holding the
 * erased byte pattern in every byte, not just the low byte of each
 * word. Pre-fix the untouched words were 0x000000FF (default
 * polarity). */
START_TEST(test_partial_page_fill_erased)
{
    uint8_t data[16];
    uint32_t addr = TC3_PFLASH_PAGE_SIZE + 32;
    int i;

    fill(data, sizeof(data), 0x40);
    ck_assert_int_eq(programBytesToErasedFlash(addr, data,
        sizeof(data)), 0);

    for (i = 0; i < 16; i++)
        ck_assert_uint_eq(g_flash[addr + i], data[i]);
    for (i = 0; i < (int)TC3_PFLASH_PAGE_SIZE; i++) {
        if (i >= 32 && i < 48)
            continue;
        ck_assert_uint_eq(g_flash[addr - 32 + i], FLASH_BYTE_ERASED);
    }
    /* The words adjacent to the data must be erased in every byte. */
    ck_assert_uint_eq(g_flash[addr - 1], FLASH_BYTE_ERASED);
    ck_assert_uint_eq(g_flash[addr + 16], FLASH_BYTE_ERASED);
}
END_TEST

/* A full-page write programs exactly the given data. */
START_TEST(test_full_page_write)
{
    uint8_t data[TC3_PFLASH_PAGE_SIZE];
    int i;

    fill(data, sizeof(data), 0x10);
    ck_assert_int_eq(programBytesToErasedFlash(TC3_PFLASH_PAGE_SIZE,
        data, sizeof(data)), 0);
    for (i = 0; i < (int)sizeof(data); i++)
        ck_assert_uint_eq(g_flash[TC3_PFLASH_PAGE_SIZE + i], data[i]);
}
END_TEST

/* cacheSector() on an all-erased sector must fill the cache with the
 * erased word value in every byte. Pre-fix the words were
 * 0x000000FF (default polarity). */
START_TEST(test_cache_sector_erased_pages)
{
    int i;

    memset(g_flash, FLASH_BYTE_ERASED, sizeof(g_flash));
    cacheSector(0);

    for (i = 0; i < WOLFBOOT_SECTOR_SIZE; i++)
        ck_assert_uint_eq(((uint8_t *)sectorBuffer)[i], FLASH_BYTE_ERASED);
}
END_TEST

/* cacheSector() on a sector with one data page keeps the data and
 * fills the erased pages with the erased pattern. */
START_TEST(test_cache_sector_mixed_pages)
{
    uint8_t pattern[TC3_PFLASH_PAGE_SIZE];
    int i;

    fill(pattern, sizeof(pattern), 0x50);
    memcpy(g_flash, pattern, sizeof(pattern));
    memset(g_flash + TC3_PFLASH_PAGE_SIZE, FLASH_BYTE_ERASED,
        sizeof(g_flash) - TC3_PFLASH_PAGE_SIZE);

    cacheSector(0);

    for (i = 0; i < (int)TC3_PFLASH_PAGE_SIZE; i++)
        ck_assert_uint_eq(((uint8_t *)sectorBuffer)[i], pattern[i]);
    for (i = TC3_PFLASH_PAGE_SIZE; i < WOLFBOOT_SECTOR_SIZE; i++)
        ck_assert_uint_eq(((uint8_t *)sectorBuffer)[i], FLASH_BYTE_ERASED);
}
END_TEST

Suite *aurix_erased_fill_suite(void)
{
    Suite *s = suite_create("aurix-erased-fill");
    TCase *tc = tcase_create("aurix-erased-fill");

    tcase_add_checked_fixture(tc, setup, teardown);
    tcase_add_test(tc, test_partial_page_fill_erased);
    tcase_add_test(tc, test_full_page_write);
    tcase_add_test(tc, test_cache_sector_erased_pages);
    tcase_add_test(tc, test_cache_sector_mixed_pages);
    suite_add_tcase(s, tc);

    return s;
}

int main(void)
{
    int fails;
    Suite *s = aurix_erased_fill_suite();
    SRunner *sr = srunner_create(s);

    srunner_run_all(sr, CK_NORMAL);
    fails = srunner_ntests_failed(sr);
    srunner_free(sr);

    return fails;
}
